GET http://127.0.0.1:4000/asdkhjgsajdhk HTTP/1.1

###
GET http://127.0.0.1:4000 HTTP/1.1

###
GET http://127.0.0.1:4000/teste HTTP/1.1

###
POST http://127.0.0.1:4000/aluno HTTP/1.1
content-type: application/json

{
    "nome": "gabriel monteiro",
    "dataNasc": "2000/01/01",
    "matricula": "SIFU"
}